name: Create Artifact (No Mod Manager) 

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache
        id: cache
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: buildCachev25

      - name: Cache
        id: cache2
        uses: actions/cache@v2.1.6
        with:
          path: Mod Manager/node_modules
          key: buildCache2v20

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Prep
        run: |
          npm install -g pkg typescript

      - name: Build EXE
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          New-Item -ItemType Directory -Force -Path ./node_modules/piscina
          robocopy ./piscina ./node_modules/piscina /COPYALL /E /is /it; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }
          tsc
          copy ./src/smf-rust.node ./compiled/smf-rust.node
          pkg package.json --targets node18-win-x64 --output Deploy.exe --compress Brotli

      - name: Ready for zip
        run: |
          New-Item -ItemType Directory dist
          New-Item -ItemType Directory dist/API
          robocopy "./For Build" ./dist /COPYALL /E; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }
          robocopy ./compiled ./dist/API /COPYALL /E *.d.ts; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }
          copy Deploy.exe dist

      - name: Zip
        uses: TheDoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d
        with:
          filename: Release.zip
          directory: dist

      - uses: actions/upload-artifact@v2
        with:
          name: Output
          path: dist/Release.zip
